name: CI-BlackDuck-SCA  # Name of the workflow

on:
  push:  # Trigger the workflow on push events
    branches: [main, master, develop, stage, release]  # Specify branches to trigger on push
  pull_request:  # Trigger the workflow on pull request events
    branches: [main, master, develop, stage, release]  # Specify branches to trigger on PR

jobs:
  build:  # Define a job named 'build'
    runs-on: [sh_mac_mdn]  # Specify the runner to execute the job
    steps:  # List of steps to execute in this job
      - name: Checkout Source  # Step to check out the repository code
        uses: actions/checkout@v4  # Use the checkout action to clone the repo

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Specify the version of Node.js you want to use

      - name: Install Dependencies
        run: npm install  # Install npm dependencies listed in package.json


      - name: Black Duck SCA Full Scan  # Step for running a full Black Duck scan
        id: black-duck-full-scan  # Unique ID for this step
        if: ${{ github.event_name != 'pull_request' }}  # Run this step only if the event is not a PR
        uses: blackduck-inc/black-duck-security-scan@v2  # Use the Black Duck security scan action
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}  # Set project name based on repo name
        with:
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}  # Black Duck server URL from environment variables
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}  # Black Duck API token from secrets
          blackducksca_scan_full: true  # Perform a full scan
          blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'  # Specify severities for scan failures
          mark_build_status: 'success'  # Mark build status as failure if issues are found

      - name: Black Duck SCA PR Scan  # Step for running a scan on pull requests
        id: black-duck-pr-scan  # Unique ID for this step
        if: ${{ github.event_name == 'pull_request' }}  # Run this step only for pull request events
        uses: blackduck-inc/black-duck-security-scan@v2  # Use the Black Duck security scan action
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}  # Set project name based on repo name
        with:
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}  # Black Duck server URL from environment variables
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}  # Black Duck API token from secrets
          blackducksca_scan_full: false  # Do not perform a full scan for PR comments
          blackducksca_prComment_enabled: true  # Enable automatic PR comments based on scan results
          github_token: ${{ secrets.BD_GITHUB_TOKEN }}  # GitHub token for authentication when posting comments