name: CI-BlackDuck-SCA
on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]
jobs:
  build:
    runs-on: [sh_mac_mdn]
  steps:
  - name: Checkout Source
    uses: actions/checkout@v4
  - name: Black Duck SCA Full Scan
    id: black-duck-full-scan
    if: ${{ github.event_name != 'pull_request' }}
    uses: blackduck-inc/black-duck-security-scan@v2
    
    ### Use below configuration to set specific detect environment variables
    env:
      DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
    with:
      blackducksca_url: ${{ vars.BLACKDUCK_URL }}
      blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
      blackducksca_scan_full: true

      ### Accepts Multiple Values
      blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'
      mark_build_status: 'failure'
      
        
  - name: Black Duck SCA PR Scan
    id: black-duck-pr-scan
    if: ${{ github.event_name == 'pull_request' }}
    uses: blackduck-inc/black-duck-security-scan@v2
    
    ### Use below configuration to set specific detect environment variables
    env:
      DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
    with:
      blackducksca_url: ${{ vars.BLACKDUCK_URL }}
      blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
      blackducksca_scan_full: false
      
      ### Below configuration is used to enable automatic pull request comment based on Black Duck SCA scan result
      blackducksca_prComment_enabled: true
      github_token: ${{ secrets.BD_GITHUB_TOKEN }}
